### ISSUE TITLE
Cannot read property '__inputResolver' of undefined

### ISSUE THREAD

**Issue by alexanderpreston** [BeIntrepid/dash-transform#1]
var pipe = new Pipe();
pipe.add(() => { return 'Hello World'; });
return pipe.execute();

Results in:
Unhandled promise rejection TypeError: Cannot read property '__inputResolver' of undefined
    at TransformNode.execute (http://localhost:9000/jspm_packages/github/beintrepid/dash-transform@0.0.6/Nodes.js:167:53)
    at http://localhost:9000/jspm_packages/github/beintrepid/dash-transform@0.0.6/Pipes.js:151:150
    at run (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:91:43)
    at http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:105:11
    at module.exports (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.invoke.js:6:25)
    at queue.(anonymous function) (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:40:9)
    at Number.run (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:27:7)
    at listner (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:31:9)

**Comment by Azim-Palmer** [comment]
Fixed
